### ISSUE TITLE
Creat script pentru automatizat colectare fisiere admitere.edu.ro

### ISSUE THREAD

**Issue by paubric** [paubric/real#2]
Asa arata API requests de la site-ul de admitere la liceu: GET `admitere.edu.ro/2018/repartizare/<judet>/data/highschool.json`.

Pentru automatizarea colectarii de fisiere de la ei, trebuie scris un Python 3 script care sa faca pentru fiecare judet din #1 niste API requests.

API requests de facut pentru fiecare judet:
GET `admitere.edu.ro/2018/repartizare/<județ>/data/highschool.json`
GET `admitere.edu.ro/2018/repartizare/<județ>/data/specialization.json`
GET `admitere.edu.ro/2018/repartizare/<județ>/data/school.json`
GET `admitere.edu.ro/2018/repartizare/<județ>/data/empty-sears.json`

Ar fi foarte util ca script-ul sa genereze un singur fisier unic cu toate datele de la toate judetele dupa modelul urmator:
```
{
...
"B": {
   "highschool": *continut highschool.json aferent*,
   "specialization": *continut specialization.json aferent*,
   "school": *continut school.json aferent*,
   "empty-seats": *continut empty-seats.json aferent*
}
...
}
```
Poate reusim sa folosim acelasi script anul viitor cu minime modificari, ar merge o functie care are ca parametri an, judet, fisier.

**Comment by sturzamihai** [comment]
On it
